<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

In this lab you will use Python (with the NumPy library) to carry out linear algebra operations.

1. Compute the scalar product of two vectors

> In mathematics, the dot product or scalar product is an algebraic operation that takes two equal-length sequences of numbers (usually coordinate vectors) and returns a single number.

> we can calculate it this way:

        a · b = ax × bx + ay × by
        
Hint: [Dot Product](https://www.mathsisfun.com/algebra/vectors-dot-product.html)

In [1]:
import numpy as np

In [2]:
a = [-12, 16]
b = [12, 9]

In [6]:
#answer:
a = np.array([-12, 16])
b = np.array([12, 9])

scalar_product = np.dot(a, b)
print(f"The scalar product of vectors a and b is: {scalar_product}")

The scalar product of vectors a and b is: 0


2. Compute the Hadamard product (entry-wise multiplication) of two vectors.

> In mathematics, the Hadamard product (also known as the Schur product[1] or the entrywise product[2]:ch. 5) is a binary operation that takes two matrices of the same dimensions and produces another matrix of the same dimension as the operands where each element i, j is the product of elements i, j of the original two matrices. It should not be confused with the more common matrix product. It is attributed to, and named after, either French mathematician Jacques Hadamard or German mathematician Issai Schur. [Wiki](https://en.wikipedia.org/wiki/Hadamard_product_(matrices))

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/4eb9bb54b2820fb3583901ec05bc4b474b6d90bc)

In [10]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
np.multiply(a,b)

array([[ 5, 12],
       [21, 32]])

In [9]:
#desired output:
# np.array([[5,12],[21,32]])

3. Compute the sum of two matrices.

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/0fb7845af355c550d44020e52699069c044126a9)

In [13]:
# Add two matrices using a nested loop

X = [[1,2,3],
    [4,5,6],
    [7,8,9]]

Y = [[2,3,7],
    [1,4,9],
    [3,2,3]]
X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

Y = np.array([[2, 3, 7],
              [1, 4, 9],
              [3, 2, 3]])

sum_matrix = X + Y
print("The sum of matrices X and Y is:")
print(sum_matrix)

The sum of matrices X and Y is:
[[ 3  5 10]
 [ 5  9 15]
 [10 10 12]]


In [ ]:
#desired output:
#[[3,5,10],
# [5,9,15],
# [10,10,12]]

4. Compute the product of two matrices.

![](https://upload.wikimedia.org/wikipedia/commons/e/eb/Matrix_multiplication_diagram_2.svg)

In [15]:
# Program to multiply two matrices using nested loops

# 3x3 matrix
X = [[7, 2, 4],
    [3, 9, 5],
    [8, 1, 6]]

# 3x4 matrix
Y = [[5,8,2,6],
    [1,4,9,3],
    [7,2,5,8]]

#X is 3 x 3, #Y is 3 x 4 matrix
#result of XY is 3 x 4 matrix.
result = [[0, 0, 0, 0],
          [0, 0, 0, 0],
          [0, 0, 0, 0]]
for i in range(len(X)):
    for j in range(len(Y[0])):
        for k in range(len(Y)):
            result[i][j] += X[i][k] * Y[k][j]

print("Result of matrix multiplication:")
for r in result:
    print(r)

Result of matrix multiplication:
[65, 72, 52, 80]
[59, 70, 112, 85]
[83, 80, 55, 99]


In [ ]:
#desired output:
#[[65, 72, 52, 80],
# [59, 70, 112, 85],
# [83, 80, 55, 99]]

5. Compute the determinant of an n x n matrix.

Hint: Use
> np.linalg.det

In [17]:
matrix = [[-2,2,-3],[-1,1,3],[2,0,-1]]
matrix = np.array([[-2, 2, -3],
                   [-1, 1,  3],
                   [ 2, 0, -1]])

determinant = np.linalg.det(matrix)
print("The determinant of the matrix is:", determinant)

The determinant of the matrix is: 17.999999999999996


6. Compute the inverse of an n x n matrix.

Hint: Use
> from numpy.linalg import inv

In [ ]:
a = np.array([[1., 2.], [3., 4.]])

In [20]:
#answer:

import numpy as np
from numpy.linalg import inv

matrix = np.array([[-2, 2, -3],
                   [-1, 1,  3],
                   [ 2, 0, -1]])
inverse_matrix = inv(matrix)
print("The inverse of the matrix is:")
print(inverse_matrix)

The inverse of the matrix is:
[[-0.05555556  0.11111111  0.5       ]
 [ 0.27777778  0.44444444  0.5       ]
 [-0.11111111  0.22222222  0.        ]]


7. (Application)
Three customers made the following purchases of three different items at an office supply store:
* Customer W bought 2 notebooks, 4 pens and 3 staplers for \$38.80
* Customer X bought 3 notebooks, 3 pens and 2 staplers for \$32.00
* Customer Y bought 4 notebooks, 8 pens and 1 stapler for \$36.60

Based on this, how much did customer Z spend in buying 1 notebook, 2 pens and 4 staplers?

In [24]:
# answer
A = np.array([[2, 4, 3],
              [3, 3, 2],
              [4, 8, 1]])
B = np.array([38.80, 32.00, 36.60])

prices = np.linalg.solve(A, B)
n, p, s = prices
cost_customer_z = 1 * n + 2 * p + 4 * s

print(f"The price of one notebook (n) is: ${n:.2f}")
print(f"The price of one pen (p) is: ${p:.2f}")
print(f"The price of one stapler (s) is: ${s:.2f}")
print(f"Customer Z spent: ${cost_customer_z:.2f}")

The price of one notebook (n) is: $3.30
The price of one pen (p) is: $1.90
The price of one stapler (s) is: $8.20
Customer Z spent: $39.90




---



---



> > > > > > > > > © 2025 Institute of Data


---



---



